# Generated by Django 3.2.6 on 2021-08-04 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('f_price', models.IntegerField()),
                ('phoneno', models.CharField(default=None, max_length=100)),
                ('address', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=100)),
                ('r_contact', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fooditem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('f_price', models.IntegerField()),
                ('f_image', models.ImageField(upload_to='media')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.restaurant')),
            ],
        ),
    ]
